FROM registry.access.redhat.com/ubi8/openjdk-17
# если будут траблы, то замени строку выше на:
# FROM openjdk-17
# в теории JDK должен подсосаться с DockerHub

ADD target/quarkus-app/lib/ /deployments/lib/
ADD target/quarkus-app/quarkus-run.jar /deployments/app.jar
ADD target/quarkus-app/app/ /deployments/app/
ADD target/quarkus-app/quarkus/ /deployments/quarkus/

CMD ["java", "-jar", "/deployments/app.jar"]
