version: '2'
services:
  db:
    container_name: 'DB'
    image: postgres
    restart: always
    ports:
      - 5428:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=LBS
#      - POSTGRES_PASSWORD=12345
      - PGDATA=/data/postgres
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/data/postgres
